// resources/js/components/icons/index.ts
export { default as EditIcon     } from './EditIcon.vue'
export { default as DeleteIcon   } from './DeleteIcon.vue'
export { default as AddIcon      } from './AddIcon.vue'
export { default as ClockIcon    } from './ClockIcon.vue'
export { default as CalendarIcon } from './CalendarIcon.vue'
export { default as PdfIcon } from './PdfIcon.vue'
export { default as ExcelIcon } from './ExcelIcon.vue'
export { default as TransferArrowsIcon } from './TransferArrowsIcon.vue'
export { default as FileLinesIcon } from './FileLinesIcon.vue'
export { default as ClipboardIcon } from './ClipboardIcon.vue'
export { default as PencilIcon } from './PencilIcon.vue'
export { default as PanelLeftOpenIcon } from './SideBar/PanelLeftOpenIcon.vue'
export { default as PanelLeftCloseIcon } from './SideBar/PanelLeftCloseIcon.vue'
export { default as FaqIcon } from './FaqIcon.vue'
export { default as ContactIcon } from './ContactIcon.vue'
// export { default as SiifIcon } from './SiifIconBC.png'
export { default as SiifIcon } from './SiifIconBC3.png'

